### ISSUE TITLE
Todo list for downloads page

### ISSUE THREAD

**Issue by DeadSix27** [ungoogled-software/ungoogled-chromium-binaries#3]
- [ ] Integrate hash files and the links into the download page.
- [ ] ^Also implement tags prob similiar to the above. [Note to myself, 2 seperate "releases"]
- [ ] Clean up the code a bit
- [ ] Add missing usage guides and refine the others
- [ ] Improve footer (currently only has copyright)

Suggestion list: (Just edit this post if you have any and add them below)
- [...]

HTML Version for reference: https://dsix.tech/uc/

**Comment by Eloston** [comment]
Closing, because this is dead.
